// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user-profiles": {
            "post": {
                "description": "Create a new user profile with preferences",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-profiles"
                ],
                "summary": "Create a new user profile",
                "parameters": [
                    {
                        "description": "User Profile Info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/user-profiles/{id}": {
            "get": {
                "description": "Get a user profile by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-profiles"
                ],
                "summary": "Get a user profile by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfile"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/voluntary/majorGroupDetails": {
            "post": {
                "description": "根据用户条件查询专业组详情",
                "consumes": [
                    "application/json",
                    "multipart/form-data",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voluntary"
                ],
                "summary": "查询专业组详情",
                "parameters": [
                    {
                        "description": "查询条件",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VoluntaryMajorGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VoluntaryMajorGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/voluntary/universityPriority": {
            "post": {
                "description": "根据用户条件查询志愿-院校优先推荐",
                "consumes": [
                    "application/json",
                    "multipart/form-data",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "voluntary"
                ],
                "summary": "查询志愿-院校优先",
                "parameters": [
                    {
                        "description": "查询条件",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VoluntaryUniversityPriorityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VoluntaryUniversityPriorityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.Preference": {
            "type": "object",
            "properties": {
                "career_interest": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "graduation_plan": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "major_preference": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "other": {
                    "type": "string"
                },
                "priority_strategy": {
                    "type": "string"
                },
                "region_preference": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_universities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tuition_preference": {
                    "type": "string"
                }
            }
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "preference": {
                    "$ref": "#/definitions/models.Preference"
                },
                "province": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserProfileRequest": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string"
                },
                "preference": {
                    "$ref": "#/definitions/models.Preference"
                },
                "province": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.VoluntaryMajor": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "专业代码",
                    "type": "string"
                },
                "id": {
                    "description": "专业id，ID 编号",
                    "type": "integer"
                },
                "min_rank": {
                    "description": "录取最低位次",
                    "type": "integer"
                },
                "min_score": {
                    "description": "录取最低分",
                    "type": "integer"
                },
                "name": {
                    "description": "专业名称",
                    "type": "string"
                },
                "plan_num": {
                    "description": "计划数",
                    "type": "string"
                },
                "probability": {
                    "description": "录取概率，百分比",
                    "type": "integer"
                },
                "strategy": {
                    "description": "策略",
                    "type": "integer"
                },
                "study_cost": {
                    "description": "学费",
                    "type": "string"
                },
                "study_year": {
                    "description": "学制",
                    "type": "string"
                },
                "year": {
                    "description": "信息年份",
                    "type": "string"
                }
            }
        },
        "models.VoluntaryMajorGroup": {
            "type": "object",
            "properties": {
                "group_code": {
                    "description": "专业组代码",
                    "type": "string"
                },
                "major": {
                    "description": "专业，专业组内全部专业",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VoluntaryMajor"
                    }
                },
                "probability": {
                    "description": "专业组概率，百分比",
                    "type": "integer"
                },
                "strategy": {
                    "description": "策略，[0冲、1稳、2保]",
                    "type": "integer"
                }
            }
        },
        "models.VoluntaryMajorGroupRequest": {
            "type": "object",
            "properties": {
                "group_code": {
                    "description": "专业组代码",
                    "type": "string"
                },
                "profile_id": {
                    "description": "档案id",
                    "type": "string"
                },
                "province": {
                    "description": "报考的省份",
                    "type": "string"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "school_code": {
                    "description": "院校代码",
                    "type": "string"
                },
                "score": {
                    "description": "分数",
                    "type": "integer"
                },
                "strategy": {
                    "description": "[0冲、1稳、2保]，默认1稳",
                    "type": "integer"
                },
                "subjects": {
                    "description": "用户选择的科目",
                    "type": "string"
                }
            }
        },
        "models.VoluntaryMajorGroupResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/models.VoluntaryMajorGroup"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string"
                }
            }
        },
        "models.VoluntaryUniversityItem": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "院校类型，综合、医药等",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "major_group": {
                    "description": "专业组，可选专业组",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VoluntaryMajorGroup"
                    }
                },
                "province": {
                    "description": "院校所在省",
                    "type": "string"
                },
                "recruit_code": {
                    "description": "院校代码",
                    "type": "string"
                },
                "tags": {
                    "description": "院校标签，例如985、211等",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "university_name": {
                    "description": "大学名称",
                    "type": "string"
                }
            }
        },
        "models.VoluntaryUniversityPriorityData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VoluntaryUniversityItem"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_num": {
                    "description": "页面总数",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页面大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总数目",
                    "type": "integer"
                }
            }
        },
        "models.VoluntaryUniversityPriorityRequest": {
            "type": "object",
            "properties": {
                "citys": {
                    "description": "选择城市，使用逗号分隔（不选择省份，仅选择城市）",
                    "type": "string"
                },
                "college_type": {
                    "description": "院校类型，使用逗号分隔，办学类型（公办），院校特色（211），院校类型（综合类），取交集",
                    "type": "string"
                },
                "enrollment_plan": {
                    "description": "招生计划，使用逗号分隔",
                    "type": "string"
                },
                "max_score": {
                    "description": "限制搜索最高分",
                    "type": "string"
                },
                "min_score": {
                    "description": "限制搜索最低分",
                    "type": "string"
                },
                "page": {
                    "description": "分页参数",
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "profile_id": {
                    "description": "档案id",
                    "type": "string"
                },
                "province": {
                    "description": "报考的省份",
                    "type": "string"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "score": {
                    "description": "分数",
                    "type": "integer"
                },
                "strategy": {
                    "description": "[0冲、1稳、2保]，默认1稳",
                    "type": "integer"
                },
                "subjects": {
                    "description": "用户选择的科目",
                    "type": "string"
                }
            }
        },
        "models.VoluntaryUniversityPriorityResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/models.VoluntaryUniversityPriorityData"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
